console.log('operator')
console.log('operator binary - membutuhkan 2 operand')
console.log('operator unary - membutuhkan 2 operand')
console.log('operator tenary - membutuhkan 3 operand')
console.log('operator assignment - operator penugas (increment, decrement dan kawna-kawna')
console.log('Urutan operasi matematika/ operator precendence bekerja pada javacsript')
console.log('boolean case sensitive')
console.log('10 == "10" true , hati!')
console.log("penambahan number + string = string")